Homework done
KhAA84/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-12 19:27 UTC by KhAA84

Сделал домашнее задание.

2021-12-14 10:52 UTC, genroelgvozo requested changes

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task1.java
> +      result.add((Person) map.get(personId));
Идея ок, но 
1) почему в мапе обджект? сразу персон нельзя? а то приводишь каждый раз
2) а давай через стрим мапу соберем, и результат тоже. Все будет красиво
3) юзай интерфейсы в типах.  Не надо писать ArrayList, пиши List

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task2.java
> +    return Stream.concat(persons1.stream(), persons2.stream())
ну тут все ок

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task3.java
> +            .collect(Collectors.toList());
так почему для createAt нельзя было Person::getCreatedAt?
если ты подумал про направление, то сейчас оно не изменилось у тебя, а так его тоже можно менять и в thenComparing(keyExtractor, Comparator.reverseOrder())
но кстати по убыванию и не просили

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task4.java
> +            .map(p -> convert(p))
1) лучше person - не жалей букв, не стоят ничего
2) лучше map(Task4::convert)

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task5.java
> +            .map(p -> convert(p, personAreaIds.get(p.getId())))
аналогично лучше person, а так все ок

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task6.java
> +    return result;
вообщем эти два блока тоже выглядят лучше через стримы)
но суть верная, так будет работать, просто многоватор строк для такого метода

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task7.java
> +            .flatMap(company -> company.getVacancies().stream())
все ок, можно еще
.map(Company::getVacancies)
.flatMap(Collection::stream)
но это на вкус

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  //Убрал remove, так как он мутирует persons, воспользовался методом skip(), разбил по строкам для читаемости
все ок

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  //тут на мой взгляд всё хорошо, разбил по строкам
ты в IDEA работаешь?) она же подсказывает)
да и я прям почти такой пример на лекции писал, тут 70% символов лишние

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  //Может лучше сделать три условия формата (first ==/!= null && second ==/!= null)
ну так перепиши как лучше
баг есть, да, нашел, но с ифами я думаю код будет еще страшнее
да и ошибиться в нем проще

А вот лекция не зря по стримам... может как можно просто?

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  //убрал ненужную проверку
почему не нужную?
А если я скажу что ты изменил поведение программы?
ну и код хочется получше сделать (но ты его выше так и писал, поэтому понятно что не стал править, но стримы тут рулят)

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return personsT.retainAll(persons2);
во-первых, прямо на лекции говорил, не надо надеяться что toList вернет изменяемую коллекцию, это плохо. Вообще изменять коллекции плохо (а ты много где add делаешь). 
есть же stream().anyMatch, а внутри contains, только навернео не list нужен для скорости (и тут не понятно почему лист, ретайн будет долго же работать)

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  // посчитал с помощью метода стримов count(), при этом избавившись от лишней переменной.
тут все верное, а почему так нельзя как было написано расскажу после дедлайна

2021-12-14 10:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    boolean codeSmellsALittleBetter = true;
хитер)

2021-12-15 15:12 UTC, KhAA84 commented on src/tasks/Task3.java
> +            .collect(Collectors.toList());
Помутнение разума, я почему-то решил, что оно мне даты правильно само по себе не отсортирует, поправлю

2021-12-15 15:14 UTC, KhAA84 commented on src/tasks/Task4.java
> +            .map(p -> convert(p))
дурацкая привычка из js. Там такое именование по типовым штукам типа arr, ind и т.п. повсюду, въелось. Поправлю. почему лучше Task4::convert хотелось бы чуть подробнее, но конечно же поправлю

2021-12-15 15:31 UTC, KhAA84 commented on src/tasks/Task6.java
> +    return result;
Как-то пока сборку сета тяжело через стримы, сам не сообразил, пришлось гуглить

2021-12-15 15:31 UTC, KhAA84 commented on src/tasks/Task8.java
> +  //тут на мой взгляд всё хорошо, разбил по строкам
IDEA вроде бы ничего не писала, но теперь уже не уверен. Тут стрим вообще не нужен был, переписал на HashSet

2021-12-15 15:31 UTC, KhAA84 commented on src/tasks/Task8.java
> +  //Может лучше сделать три условия формата (first ==/!= null && second ==/!= null)
переписал на Stream.of

2021-12-15 15:34 UTC, KhAA84 commented on src/tasks/Task8.java
> +  //убрал ненужную проверку
Изменил, понял о чём ты, переписал на стрим с выбором первого вхождения при сборке в мап.

2021-12-15 15:36 UTC, KhAA84 commented on src/tasks/Task8.java
> +    return personsT.retainAll(persons2);
понял, я хотел как раз добиться поведения anyMatch, но не нашел сам anyMatch, обещаю проштудировать Stream API от корки до корки =) 
про лист понял о чём ты ;)

2021-12-15 17:32 UTC, KhAA84 commented on src/tasks/Task8.java
> +  //Rf
случайно затёр комментарий и не обратил внимание. Переписал на HashSet

2021-12-17 09:08 UTC, genroelgvozo approved these changes

2023-04-10 05:03 UTC, merged